title: Tajul Islam
description: Full Stack Developer Portfolio
theme: jekyll-theme-minimal

# Optional base settings
url: "https://taj54.github.io" 
baseurl: ""                            # Leave empty for user/organization pages

permalink: /blog/:title/

paginate: 5         # number of posts per page
paginate_path: "/blog/page:num"

# Scope default layout for specific folder
defaults:
  - scope:
      path: "vsc_extension"
    values:
      layout: extension

# Markdown parser
markdown: kramdown

# Plugins (optional, GitHub supports these natively)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate



# Exclude dev files from build
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .github

# Author metadata (optional)
author:
  name: Taj
  email: tajulislamj200@gmail.com
  github: taj54
  linkedin: tajulislam-j
