version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:cached
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >
      sh -c "bundle install &&
             bundle exec jekyll serve --watch --force_polling --drafts --host 0.0.0.0"
